server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mvc:
    format:
      date: yyyy-MM-dd

mybatis-plus:
  configuration:
    global-config:
      db-config:
        logic-delete-field: delFlag
        logic-delete-value: 1
        logic-not-delete-value: 0
        id-type: auto
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

oss:
  accessKey: qApgF9thMR0VUuestbO4Wg8sZ_es75IxEoLqqaBU
  secretKey: xw_Z3XEGYAy3Ccz2qAZVsxVL8H0qqWuw4EAC73Sz
  bucket: java-wy-blog
